"""Recover a Qdrant that will not start because its storage is corrupt.

    python scripts\\recover_storage.py            # show what it would do
    python scripts\\recover_storage.py --yes      # actually do it

Why this is needed
------------------
On Windows the storage directory is a bind mount (see docker/compose.yml for
why: it keeps the vectors off a full C: drive). Docker Desktop translates
Windows paths through a filesystem layer that does not provide the write
ordering and mmap semantics Qdrant's on-disk index relies on -- Qdrant itself
warns about this at startup:

    WARN There is a potential issue with the filesystem for storage path
         /qdrant/storage. Details: Unrecognized filesystem

If the machine loses power, Docker is killed, or WSL2 is shut down mid-write,
an index can be left torn. Qdrant then panics on load and the container
restarts forever:

    Failed to load local shard "/qdrant/storage/collections/code/0"
    Failed to deserialize document: invalid type: integer `0`, expected struct

What this does about it
-----------------------
`code` and `docs` are DERIVED: every point in them is regenerated by
re-indexing your projects, so deleting a corrupt one costs only the time to
rebuild it. This script deletes those, restarts Qdrant, and lets setup
recreate and re-index them.

`memory` is NOT derived -- it holds authored knowledge that nothing can
regenerate. This script never deletes it. If `memory` is the corrupt
collection, it says so and points you at the JSON export instead
(scripts/import_memory.py), which exists for exactly this.

Stdlib-only and imports nothing from the project, so it works on a machine
whose environment is half-built.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import socket
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STORAGE = ROOT / "data" / "qdrant" / "storage"
COLLECTIONS = STORAGE / "collections"
CONTAINER = "rememory-qdrant"

# Rebuildable by re-indexing; safe to delete. `memory` is deliberately absent.
DERIVED = ("code", "docs")
PROTECTED = "memory"

NO_WINDOW = {"creationflags": 0x08000000} if sys.platform == "win32" else {}


def docker(*args: str, timeout: int = 60):
    try:
        return subprocess.run(
            ["docker", *args], capture_output=True, text=True,
            timeout=timeout, check=False, **NO_WINDOW,
        )
    except (OSError, subprocess.SubprocessError):
        return None


def qdrant_port() -> int:
    # Same precedence as indexer/runtime.py: default <- runtime.json <- env.
    # Ignoring REMEMORY_QDRANT_PORT made a SUCCESSFUL recovery poll the wrong
    # port for 60s and then report failure on machines using the override.
    import contextlib

    port = 6333
    path = ROOT / "config" / "runtime.json"
    if path.exists():
        with contextlib.suppress(ValueError, OSError, TypeError):
            port = int(json.loads(path.read_text(encoding="utf-8")).get("qdrant_port", port))
    env = os.environ.get("REMEMORY_QDRANT_PORT", "")
    if env.isdigit():
        port = int(env)
    return port


def wait_ready(port: int, seconds: int = 60) -> bool:
    """Wait for the port to accept connections, giving up after `seconds`.

    Short on purpose: a Qdrant that is going to start does so in a few
    seconds, so a long window only makes a failure slower to report.
    """
    deadline = time.time() + seconds
    while time.time() < deadline:
        try:
            with socket.create_connection(("127.0.0.1", port), timeout=3):
                return True
        except OSError:
            time.sleep(2)
    return False


def corrupt_collections_from_logs() -> set[str]:
    """Which collections does Qdrant say it failed to load?"""
    logs = docker("logs", "--tail", "400", CONTAINER)
    found: set[str] = set()
    if logs is None:
        return found
    text = (logs.stdout or "") + (logs.stderr or "")
    marker = '/qdrant/storage/collections/'
    for line in text.splitlines():
        if "Failed to load" not in line or marker not in line:
            continue
        rest = line.split(marker, 1)[1]
        name = rest.split("/", 1)[0].strip('"')
        if name:
            found.add(name)
    return found


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--yes", action="store_true", help="actually delete and restart")
    parser.add_argument(
        "--no-start",
        action="store_true",
        help="delete only; leave the container stopped for the caller to recreate",
    )
    args = parser.parse_args()

    print("rememory storage recovery\n")
    if not COLLECTIONS.exists():
        print(f"  No storage at {COLLECTIONS} -- nothing to recover.")
        print("  Run setup to create a fresh database.")
        return 0

    corrupt = corrupt_collections_from_logs()
    print(f"  storage    {COLLECTIONS}")
    print(f"  corrupt    {', '.join(sorted(corrupt)) if corrupt else '(none named in the logs)'}")

    if PROTECTED in corrupt:
        print()
        print(f"  REFUSING TO CONTINUE: '{PROTECTED}' is the corrupt collection.")
        print("  It holds authored knowledge that re-indexing cannot regenerate, so")
        print("  this script will not delete it. Restore it from your export instead:")
        print()
        print("      python scripts\\import_memory.py")
        print()
        print("  The newest export is in data\\backups. If you have no export, copy")
        print(f"  {COLLECTIONS / PROTECTED} somewhere safe and delete it by hand only")
        print("  once you have accepted that its contents are gone.")
        return 2

    # Delete every derived collection, not just the one that happened to be
    # named first: Qdrant panics on the first bad shard it meets and stops
    # looking, so a second corrupt collection would only surface on the next
    # start, turning recovery into a guessing game.
    targets = [c for c in DERIVED if (COLLECTIONS / c).exists()]
    if not targets:
        print("\n  No derived collections on disk -- nothing safe to remove.")
        return 1

    print(f"  will delete {', '.join(targets)}  (rebuilt by re-indexing)")
    print(f"  will keep   {PROTECTED}  (cannot be regenerated)")

    if not args.yes:
        print("\n  Dry run. Re-run with --yes to proceed.")
        return 0

    print("\n  stopping the container...")
    docker("stop", CONTAINER, timeout=90)

    for name in targets:
        path = COLLECTIONS / name
        try:
            shutil.rmtree(path)
            print(f"  deleted {path}")
        except OSError as exc:
            print(f"  FAILED to delete {path}: {exc}")
            print("  Close anything holding those files (antivirus, Explorer) and retry.")
            return 1

    if args.no_start:
        # setup recreates the container itself with `docker compose up`, which
        # is the only way to pick up a changed published port. Starting the old
        # one here would just fail to bind and look like recovery had failed.
        print("\n  Deleted. Leaving the container stopped for setup to recreate.")
        return 0

    print("  starting the container...")
    started = docker("start", CONTAINER, timeout=90)
    if started is None or started.returncode != 0:
        print("  Could not start the container. Run setup.ps1 / setup.sh to recreate it.")
        return 1

    port = qdrant_port()
    print(f"  waiting for Qdrant on 127.0.0.1:{port}...")
    if not wait_ready(port):
        print("\n  Qdrant still did not come up. Check: docker logs rememory-qdrant")
        print("  If it names 'memory' as corrupt, restore it with scripts/import_memory.py.")
        return 1

    print("\n  Recovered. Re-run setup (or 'uv run -m indexer.cli index --project <name>')")
    print("  to rebuild the deleted collections.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
